### ISSUE TITLE
[QUESTION] Always baby/small

### ISSUE THREAD

**Issue by AggerTV** [brainsynder-Dev/SimplePets#101]
**Please put your question below**
Hello there, how would I do so that whenever a player spawns a pet, it's by default a baby pet, and they can't change that? And further, how would I do this for only certain types of pets?

I'm sorry if this is really obvious and I completely missed it, and thank you in advance :)

**Comment by Thatsmusic99** [comment]
It's fine, I'll be writing down a full answer regardless since this is a common query we have, but also requires a lot of steps to go through.

### Making the pet small by default
In every .json file for pets, there is an option called `on_summon`, which is represented as an array:
```json
on_summon: [],
```
To force the pet to be a baby as it spawns in, just add the following line in between the square brackets:
```json
on_summon: [
    "pet modify {player} {'baby':true}"
],
```
This simply runs the /pet modify command through console and changes the pets' entity data.

This has to be done for each pet, hence you can make it only happen for some pets.

### Stopping players from changing the age
This is a relatively straightforward one, you may find a permissions plugin handy for this.

If you want absolutely no players to be able to change the age of the pet, search for the following item in the .json file of the pet (inside the `data-items` array):
```json
"age": [
      {
        "material": "WHEAT",
        "meta": {
          
        },
        "name": "&6Baby: &e%value%"
      }
    ],
```

And simply remove it, that's it. If it's the last item in the array and there's an item above it, be sure to remove the trailing comma that appears.

However, if you want certain players to access it, make sure your config option, `Needs-Data-Permissions`, is set to true, and give them access to `pet.type.bee.data.age` as an example. However, if you have given `pet.type.bee.data.*` to all players, be sure to negate `pet.type.bee.data.age` for the players you don't want to have it, and explicitly add it for those you do want to access it.

Let me know if I need to go over anything. Cheers in advance!

**Comment by AggerTV** [comment]
Thank you so much, this was really helpful!
