### ISSUE TITLE
[FEATURE REQUEST] Add support for Polish for letters like: łęćżść

### ISSUE THREAD

**Issue by arturek1666** [brainsynder-Dev/SimplePets#103]
**Is your feature request related to a issue? Please describe.**
I would love to be able to use this letters ` łęćżść` as currently every time I do add that into language it replaces with ?? after restart.

**Comment by arturek1666** [comment]
Just to update it works in other file like config or inside pets folders if i add them it's fine, the issue is only with Messages.yml
You add polish letters you restart server join and open file again and polish letters become '??'

**Comment by Thatsmusic99** [comment]
Please make sure your file is saving in the correct encoding (tested using UTF-8) and not edited using a shared host file editor. I wasn't able to reproduce this one.

![](https://i.gyazo.com/1de5a27b3e79c917716ab7b55c17a07d.png)

**Comment by arturek1666** [comment]
Interesting, well it does work yes, but did you check the file, and restart server?
As yes it does work at first but if you check the file after restart it should change to ??
At least that's what is happening on paperspigot 1.16.5
And that's the issue, it basically means every restart i have to replace file with new one xD 
So in short terms:
It loads, but on text load of messages change ;( to ?? if format not supported. Not sure why it's happening but other plugin had the same issue after some spigot or papermc updates.

**Comment by Thatsmusic99** [comment]
Tested using Paper Build 576 (1.16.5), restarted the server 3 times, checked the file each time, tested in game as well, the file did not change whatsoever.

If it's happening with other plugins as well, it isn't solely SimplePets problem. If you're on a shared host, you will most likely need to open a ticket, since I have seen this kind of thing happen before. You can also try updating your Paper version if it's outdated but I don't believe the Bukkit config system has changed for a long time.

**Comment by arturek1666** [comment]
Well there was issue with other plugin but author of that plugin fix it. 
For some reason it dosn't happen in the pets category or config.yml butjust messages.yml for some reason..

**Comment by mibac138** [comment]
I have opened a PR for BSLib which is where the issue stems from. @Thatsmusic99 I'm pretty sure it works for you because your default charset is UTF_8 or something compatible, however that's not the same for every system and that explains how for @arturek1666 this didn't work yet you had no problems whatsoever
