### ISSUE TITLE
Paper 1.17 #46

### ISSUE THREAD

**Issue by James-Cotterill** [brainsynder-Dev/SimplePets#110]
### What steps will reproduce the problem?
1. Paper1.17   46
2. SimplePets Build 70

### What were you expecting to happen? What happened instead?
Plugin to run

### Could you please do *"/pet debug"* and paste the link here:
Not running

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
https://pastebin.com/X1vLr1wx

### Have you tried one of our development builds? *(If no, then please check if there is one [here](https://discord.gg/9kqYDaV) and give it a try)*: 
Yes

### Additional information? *(Did it work in previous versions? etc.)*
Yes

**Comment by Thatsmusic99** [comment]
So, many things.

v4.4 is not meant to run on 1.17. [v5, however, is.](https://ci.pluginwiki.us/job/SimplePets_v5/)

Although, it does not work on Paper 1.17 due to a mappings issue that has yet to be resolved but is being followed by PaperMC/paperweight#24.

The plugin will not work until said mappings problem is fixed and we have no ETA on that and I don't think the Paper team do either.

**Comment by Thatsmusic99** [comment]
Fixed in [v5 Build 49](https://ci.pluginwiki.us/job/SimplePets_v5/49/)
