### ISSUE TITLE
[BUG] SimplePets error in console after selecting goat pet (from goat NPC)

### ISSUE THREAD

**Issue by cloakfox** [brainsynder-Dev/SimplePets#123]
Please drop the link generated from doing `/pet debug` here
https://www.pastelog.us/etifijiyej

**Describe the bug**
https://gist.github.com/cloakfox/748df89219e7c8bd09a86c4012052ea2

Goat NPC also disappeared with this error (Citizens)

Paper 1.17.1

**Comment by Thatsmusic99** [comment]
Reproduced successfully by placing a normal MC mob next to the pet. Will see if I can trick the server into *not* throwing that error unless it just makes everything worse.

**Comment by Thatsmusic99** [comment]
Confirmed to be fixable, but will hold back on merging the PR for now since I want to check another problem that had risen to see if the two problems are related. I also want to check to make sure that the solutions proposed works nicely with the rest of the plugin and other plugins since it's quite a hacky but thankfully simple workaround.

If it works, you can reference the fix to the Citizens developers as well, assuming they're fine with making fixes like this.
