### ISSUE TITLE
[Bug]: Permission error with 1.19 mob pets

### ISSUE THREAD

**Issue by iLemon** [brainsynder-Dev/SimplePets#195]
### Debug Log

https://www.pastelog.us/umapatopac

### What happened?

I'm having issues where players cannot spawn in their 1.19 mob pets, such as the Allay, when setting the permission like `pet.type.allay.*`

This permission format works for all the other old mobs, just not the new mobs.

![image](https://user-images.githubusercontent.com/18317307/183062087-e56201a9-4550-4cc7-869b-07796cd0549e.png)
![image](https://user-images.githubusercontent.com/18317307/183062126-2456d293-b497-459c-8d3e-eb5d33ea7c4b.png)

### Steps To Reproduce

1. Grant permission `pet.type.allay.*`
2. Attempt /simplepet summon Allay
3. It should give a no-permission message

### Up-To-Date

- [X] I am using the latest build

**Comment by Thatsmusic99** [comment]
Use pet.type.allay instead, permissions have never worked like this. Let us know if that fails too.

**Comment by iLemon** [comment]
> Use pet.type.allay instead, permissions have never worked like this. Let us know if that fails too.

It works fine without the `.*`. I've always done it this way so that players can wear the pet as their hat, mount or fly:
![image](https://user-images.githubusercontent.com/18317307/183062829-5ef5bd79-1ac2-4d1c-a127-dfe0adb1c6f3.png)

How are these permissions handled these days?

**Comment by Thatsmusic99** [comment]
pet.type.entity.* will cover all grounds for hats and mounts, but I believe on its own without the .* it's just for spawning. It's just how permissions are treated by plugins and Bukkit generally. For example, here is the wiki page for Enderman permissions: https://wiki.bsdevelopment.org/permissions/pet-permissions/enderman

I believe it's similar to v4 but I cannot say for prior versions like v3 since I did not have as much involvement with those versions.

I've seen this brought up prior so I may consider bringing it up with Brian to help with accessibility, but maintain backwards compatibility.

**Comment by iLemon** [comment]
I think at some point recently, the `pet.type.<mob>.*` permission no longer includes spawning. Weirdly I'm only seeing this with 1.19 mobs, all the older mobs work fine.
