### ISSUE TITLE
Pets vanish / respawn when executing any WorldEdit command

### ISSUE THREAD

**Issue by Od1e** [brainsynder-Dev/SimplePets#56]
### What steps will reproduce the problem?
1. Summon any pet
2. Input any WorldEdit command
(Video of issue: https://streamable.com/i45l3)

### Could you please do *"/pet debug"* and paste the link here:
https://pastebin.com/5ghXmMQW (HasteBin wouldn't work)

### Have you tried one of our development builds? *(If no, then please check if there is one [here](https://discord.gg/9kqYDaV) and give it a try)*: 
Yes, I have used both the current stable build and one of the more recent development builds

### Additional information? *(Did it work in previous versions? etc.)*
Certain pets will completely vanish (ex. bee), while other pets would just vanish for a second and then reappear (ex. cow, armorstand, etc.)

**Comment by Thatsmusic99** [comment]
Looking at the code in SimplePets, this appears to be a feature instead of a bug, since WorldEdit can duplicate pets - so to avoid this, the pets are completely removed so they can't be included in the WorldEdit selection. This only applies to the command sender's pet, which may cause some problems itself.

**Comment by anony55** [comment]
I see. In that case, the feature works fine with other pets as they immediately re-appear, but is the bee pet completely vanishing a bug?

**Comment by Thatsmusic99** [comment]
As far as I know, they're not even meant to reappear.
