### ISSUE TITLE
Error from Armor Stand Pet

### ISSUE THREAD

**Issue by swim709** [brainsynder-Dev/SimplePets#90]
### What steps will reproduce the problem?
1. Install Simple Pets
2. Install Graves  (https://www.spigotmc.org/resources/graves.74208/)
3.  Summon Armor Stand Pet

### What were you expecting to happen? What happened instead?
When a player summons an Armor Stand Pet, it seems to work ok but the console gets flooded with errors. They point towards a conflict with another plugin called Graves. I will print it to the attention of that dev as well but not sure on which side the problem is on.

### Could you please do *"/pet debug"* and paste the link here:
https://hastebin.com/hecuguxuna 

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
https://pastebin.com/VLveFa6B
-Search for "/pets summon armor_stand" to see where the errors start.

### Additional information? *(Did it work in previous versions? etc.)*
It's been like this as long as I can remember.

**Comment by Thatsmusic99** [comment]
I would advise talking to the developers first as you mentioned, due to SP's code structure, there's not a lot we can do about it. The developers can work around it though by checking if the entity is an instance of ArmorStand rather than immediately casting it, which is what they appear to be doing.
