### ISSUE TITLE
Nametag showing as "&a&l{name}'s pet" Instead of being bold green.

### ISSUE THREAD

**Issue by MattGodwin** [brainsynder-Dev/SimplePets#94]
### What steps will reproduce the problem?
1. Install the plugin.
2. Spawn any pet
3. 

### What were you expecting to happen? What happened instead?
The nametag of the pet should be bold green.

### Could you please do *"/pet debug"* and paste the link here:
https://pastebin.com/1fAb7fAe

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
No errors shown in console.

### Have you tried one of our development builds? *(If no, then please check if there is one [here](https://discord.gg/9kqYDaV) and give it a try)*: 
I'm using the experimental build because the main build is broken.

### Additional information? *(Did it work in previous versions? etc.)*
This is a completely clean install of the plugin and I haven't touched the config or anything..

**Comment by MattGodwin** [comment]
Renaming the pet fixed the issue although it is very inconvenient and it would be better if it worked out of the box..

**Comment by Thatsmusic99** [comment]
This should now be fixed in the latest build. This one took a while to do, not because of the fact that updating the library was a pain in the backend, but because Brian's been busy with the newer version and I've personally tried to avoid touching too much of the code (because it's not going to last anyway), but had some free time and decided to patch it.

This should've fixed a lot of other issues that were present in the plugin. I have one more patch to make then all known (solvable) issues should be addressed.
